platform :ios, '10.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

target 'Upnextbus' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'react-native-maps', path: rn_maps_path
  # pod 'react-native-google-maps', path: rn_maps_path # uncomment if want google-maps support on ios
  # pod 'GoogleMaps' # uncomment if want google-maps support on ios
  # pod 'Google-Maps-iOS-Utils' # uncomment if want google-maps support on ios

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  # target 'UpnextbusTests' do
  #   inherit! :complete
     # Pods for testing
  # end

  use_unimodules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end